version: '3'

services:
    nginx:
        image: nginx:1.12-alpine
        container_name: cqrs_codely_tv_nginx
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./etc/infrastructure/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        image: jorge07/alpine-php:7.1-dev
        container_name: cqrs_codely_tv_php
        ports:
            - "2244:22"
            - "9000:9000"
        volumes:
            - "$PWD:/app"
        environment:
            - PHP_IDE_CONFIG=serverName=CodelyCQRSCourse
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: cqrs_codely_tv_mysql
        ports:
            - "3306:3306"
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${CODELYTV_CQRS_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${CODELYTV_CQRS_MYSQL_DATABASE}
            MYSQL_USER: ${CODELYTV_CQRS_MYSQL_USER}
            MYSQL_PASSWORD: ${CODELYTV_CQRS_MYSQL_PASSWORD}