version: '3'

services:
  shared_rabbitmq:
    container_name: codelytv-php_ddd_skeleton-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=codelytv
      - RABBITMQ_DEFAULT_PASS=c0d3ly

  shared_prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9999:9090

  mooc_mysql:
    container_name: codelytv-php_ddd_skeleton-mooc-mysql
    image: mysql:8
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  backoffice_elasticsearch:
    container_name: codelytv-php_ddd_skeleton-backoffice-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  backoffice_backend_php:
    container_name: codelytv-php_ddd_skeleton-backoffice_backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9040:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - shared_prometheus
      - backoffice_elasticsearch

  backoffice_backend_nginx:
    container_name: codelytv-php_ddd_skeleton-backoffice_backend-nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8040:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/backoffice_backend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backoffice_backend_php

  backoffice_frontend_php:
    container_name: codelytv-php_ddd_skeleton-backoffice_frontend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9041:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - shared_prometheus

  backoffice_frontend_nginx:
    container_name: codelytv-php_ddd_skeleton-backoffice_frontend-nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8041:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/backoffice_frontend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backoffice_frontend_php

  mooc_backend_php:
    container_name: codelytv-php_ddd_skeleton-mooc_backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9030:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - shared_prometheus
      - mooc_mysql

  mooc_backend_nginx:
    container_name: codelytv-php_ddd_skeleton-mooc_backend-nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/mooc_backend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mooc_backend_php
