CodelyTv\CodelyTv\Context\Video\Module\VideoLike\Domain\VideoLike:
  type: entity
  table: video_like

  id:
    id:
      type: video_like_id
      column: id
      length: 36

  fields:
    videoId:
      type: video_id
      column: video_id
    userId:
      type: user_id
      column: user_id