services:
  _defaults:
    autoconfigure: true

  # Command Handlers

  codely.video.video.command_handler.create_video:
    class: CodelyTv\Context\Video\Module\Video\Application\Create\CreateVideoCommandHandler
    arguments:
      - '@codely.video.video.video_creator'

  codely.video.video.command_handler.update_video_title:
      class: CodelyTv\Context\Video\Module\Video\Application\Update\UpdateVideoTitleCommandHandler
      arguments:
        - '@codely.video.video.video_title_updater'


  # Query Handlers

  codely.video.video.query_handler.find:
    class: CodelyTv\Context\Video\Module\Video\Application\Find\FindVideoQueryHandler
    arguments:
      - '@codely.video.video.video_finder'


  # Services

  codely.video.video.video_creator:
    class: CodelyTv\Context\Video\Module\Video\Application\Create\VideoCreator
    arguments:
     - '@codely.video.video.repository'
     - '@codely.video.domain_event_publisher'

  codely.video.video.video_title_updater:
    class: CodelyTv\Context\Video\Module\Video\Application\Update\VideoTitleUpdater
    arguments:
     - '@codely.video.video.repository'

  codely.video.video.video_finder:
    class: CodelyTv\Context\Video\Module\Video\Application\Find\VideoFinder
    arguments:
     - '@codely.video.video.repository'
