video_post:
  path:     /video
  defaults: { _controller: codely.mooc_backend.controller.video.post }
  methods:  [POST]

video_get:
  path:     /video/{id}
  defaults: { _controller: codely.mooc_backend.controller.video.get }
  methods:  [GET]

video_patch:
  path:     /video/{videoId}/description
  defaults: { _controller: codely.mooc_backend.controller.video.description.patch }
  methods:  [PATCH]