video_post:
  path:     /video
  defaults: { _controller: codely.mooc_backend.controller.video.post }
  methods:  [POST]

video_get:
  path:     /video/{id}
  defaults: { _controller: codely.mooc_backend.controller.video.get }
  methods:  [GET]

videos_get:
  path:     /video
  defaults: {_controller: codely.mooc_backend.controller.videos.get }
  methods: [GET]
