video_post:
  path:     /video
  defaults: { _controller: codely.api.controller.video.post }
  methods:  [POST]

video_get:
  path:     /video/{id}
  defaults: { _controller: codely.api.controller.video.get }
  methods:  [GET]

video_like:
  path: /video/like/{id}
  defaults: { _controller: codely.api.controller.video.like.post }
  methods:  [POST]